Fix sast issues
QtExcel/QXlsx pull request #230
Opened 2022-08-29 14:20 UTC by ProjectMutilation

Hi! I found some potential bugs and code smells in your code
In this PR fixes of these problems.
P.S. every commit message is  short description of a bug

2022-08-29 14:34 UTC, dantti commented on QXlsx/header/xlsxcellrange.h
> +        if (this != &other) {
Sorry, don't agree with this, it adds branching which is likely to just make the code slower for 99% of the case where the range is different.

2022-08-29 14:34 UTC, dantti commented on QXlsx/source/xlsxabstractooxmlfile.cpp
> +    if(relationships){
please add space after if

2022-08-29 14:35 UTC, dantti commented on QXlsx/source/xlsxcellformula.cpp
> +    if (this != &other) {
again same unneeded optimization

2022-08-29 14:36 UTC, dantti commented on QXlsx/source/xlsxchartsheet.cpp
> +        QSharedPointer<DrawingAbsoluteAnchor> anchor = QSharedPointer<DrawingAbsoluteAnchor>(new DrawingAbsoluteAnchor(drawing(), DrawingAnchor::Picture));
Better create the item on stack if it's to be deleted at the end of the scope.

2022-08-29 14:37 UTC, dantti commented on QXlsx/source/xlsxconditionalformatting.cpp
> +    if (this != &other) {
same

2022-08-29 14:48 UTC, dantti commented on QXlsx/source/xlsxdrawing.cpp
> +                QSharedPointer<DrawingAbsoluteAnchor> anchor = QSharedPointer<DrawingAbsoluteAnchor>(new DrawingAbsoluteAnchor(this));
This might make the code crash as this is appended to a list, QSharedPointer doesn't do magic to fix memory issues.

2022-08-29 14:49 UTC, dantti requested changes
I'd rather have this as smaller PRs we can commit what makes sense.

2022-08-30 05:43 UTC, ProjectMutilation commented on QXlsx/header/xlsxcellrange.h
> +        if (this != &other) {
I don't agree with your opinion, one of secure programming rules of SEI CERT C++ Coding Standard "[OOP54-CPP. Gracefully handle self-copy assignment](https://wiki.sei.cmu.edu/confluence/display/cplusplus/OOP54-CPP.+Gracefully+handle+self-copy+assignment)"  
Maybe then should changing to copy-and-swap idiom?

2022-08-30 05:52 UTC, ProjectMutilation commented on QXlsx/source/xlsxchartsheet.cpp
> +        QSharedPointer<DrawingAbsoluteAnchor> anchor = QSharedPointer<DrawingAbsoluteAnchor>(new DrawingAbsoluteAnchor(drawing(), DrawingAnchor::Picture));
I thought at first to do this, but I used QSharedPointer, because it is used everywhere in the function

2022-08-30 06:08 UTC, ProjectMutilation commented on QXlsx/header/xlsxcellrange.h
> +        if (this != &other) {
In general, this class is a POD type, the compiler itself will create the correct copy constructor and assignment operator.
You can remove the explicit definition and the compiler will generate the optimal solution

2022-08-30 06:13 UTC, ProjectMutilation commented on QXlsx/source/xlsxdrawing.cpp
> +                QSharedPointer<DrawingAbsoluteAnchor> anchor = QSharedPointer<DrawingAbsoluteAnchor>(new DrawingAbsoluteAnchor(this));
QSharedPointer will delete the pointer it is holding when it goes out of scope, provided no other QSharedPointer objects are referencing it. It isn't magic but it is safer than raw pointers

2022-08-30 10:15 UTC, dantti commented on QXlsx/source/xlsxdrawing.cpp
> +                QSharedPointer<DrawingAbsoluteAnchor> anchor = QSharedPointer<DrawingAbsoluteAnchor>(new DrawingAbsoluteAnchor(this));
It's not safer, you still need to properly handle memory and it's not the case here:

https://github.com/QtExcel/QXlsx/blob/master/QXlsx/source/xlsxdrawinganchor.cpp#L55

The raw pointer is appended to the parent, and you are not assigning anchor to anything else so it will be deleted 2 lines after it's creation, leaving a dangling pointer.

2022-08-30 10:19 UTC, dantti commented on QXlsx/header/xlsxcellrange.h
> +        if (this != &other) {
That link would only apply to this case if the class was holding pointers, this class only caries int's so no use, and as you said, it doesn't even need the copy operator.

2022-08-30 10:55 UTC, ProjectMutilation commented on QXlsx/source/xlsxdrawing.cpp
> +                QSharedPointer<DrawingAbsoluteAnchor> anchor = QSharedPointer<DrawingAbsoluteAnchor>(new DrawingAbsoluteAnchor(this));
Ok, i'll revert this commit

2022-08-30 11:00 UTC, ProjectMutilation commented on QXlsx/header/xlsxcellrange.h
> +        if (this != &other) {
I don't agree, but I'll revert the commit in this pr.
Self-assigment check is a good practice, maybe we'll come back to this issue later.

2022-08-30 11:03 UTC, dantti commented on QXlsx/source/xlsxchartsheet.cpp
> +        QSharedPointer<DrawingAbsoluteAnchor> anchor = QSharedPointer<DrawingAbsoluteAnchor>(new DrawingAbsoluteAnchor(drawing(), DrawingAnchor::Picture));
for the record this has the same dangling pointer issue

2022-08-30 11:04 UTC, dantti commented on QXlsx/source/xlsxconditionalformatting.cpp
> +                    rule->attrs[XlsxCfRuleData::A_cfvo3] = QVariant::fromValue(data);
I don't know what this does

2022-08-30 11:09 UTC, ProjectMutilation commented on QXlsx/source/xlsxconditionalformatting.cpp
> +                    rule->attrs[XlsxCfRuleData::A_cfvo3] = QVariant::fromValue(data);
I think that here is typo, otherwise the condition does not make sense
it is similar on construction on lines 558-563

2022-08-30 11:18 UTC, ProjectMutilation commented on QXlsx/source/xlsxchartsheet.cpp
> +        QSharedPointer<DrawingAbsoluteAnchor> anchor = QSharedPointer<DrawingAbsoluteAnchor>(new DrawingAbsoluteAnchor(drawing(), DrawingAnchor::Picture));
reverted

2022-08-30 12:44 UTC, merged