fix(workbook): fix abs path  /xl/worksheets/sheet1.xml -> xl/worksheets/sheet1.xml
QtExcel/QXlsx pull request #332
Opened 2024-05-10 07:18 UTC by stolen-programmer

fix abs path  /xl/worksheets/sheet1.xml -> xl/worksheets/sheet1.xml

2024-05-10 11:28 UTC, dantti commented on QXlsx/source/xlsxworkbook.cpp
> +                if (relationship.target.startsWith(QString::fromUtf8("/"))) {
please replace costy fromUtf8 with u'/' and can you explain why this change is needed?

2024-05-10 13:34 UTC, stolen-programmer commented on QXlsx/source/xlsxworkbook.cpp
> +                if (relationship.target.startsWith(QString::fromUtf8("/"))) {
I am unable to read an xlsx
Through breakpoint localization
Confirmed that files starting with/cannot be read

2024-05-10 13:43 UTC, dantti commented on QXlsx/source/xlsxworkbook.cpp
> +                if (relationship.target.startsWith(u"/")) {
it's a single char use u'/'

2024-05-10 13:43 UTC, stolen-programmer commented on QXlsx/source/xlsxworkbook.cpp
> +                if (relationship.target.startsWith(QString::fromUtf8("/"))) {
You can take a look at the details
#305

2024-07-04 13:19 UTC, dantti requested changes

2024-07-04 13:19 UTC, dantti commented on QXlsx/header/xlsxworksheet.h
> +    const QList<CellRange> &editRegion() const;
Please change to:
QList<CellRange> editRegion() const;
as const & return in Qt containers is not needed

2024-07-04 13:19 UTC, dantti commented on QXlsx/source/xlsxworksheet.cpp
> +                        // 跨多行
Please leave comments in english.

2024-07-04 13:19 UTC, dantti commented on QXlsx/header/xlsxworksheet.h
> +    const QList<CellRange> &editRegion() const;
also since this is plublic plese move upwards and leave a description documenting it

2024-07-05 03:21 UTC, closed without merging